### ISSUE TITLE
Hãy ghi đúng tác giả Bình Phan vào.

### ISSUE THREAD

**Issue by BeanGTA** [KaysilGVN/AcidIsland#1]
Sẽ bị bản quyền xóa nếu không thêm Bình Phan

Thêm nữa hãy update tính năng mới, cái này nó đã bị lỗi claim nên sài hệ thống mới của myplot và thêm plugins spoondetector để chạy myplot mới nhất

yêu cầu thay đổi cấu trúc chuyển dịch, yêu cầu thay đổi cấu trúc của lệnh

plugins này bên mình đã fix và hoạt động tốt ở bản 1.8 nên sẽ không bị lỗi claim , nếu bạn muốn hãy liên hệ fb.com/tien060701 để bản mới đc fix đăng lên

**Comment by KaysilGVN** [comment]
fix hết r bác ạ :v còn để tác giả thì để e thêm vô :v

**Comment by BeanGTA** [comment]
ừm
